# Generated by Django 4.1 on 2024-05-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harmoniconnect", "0002_serviceprovider_average_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceprovider",
            name="name",
            field=models.CharField(default="Provider name", max_length=255),
        ),
    ]
