# Generated by Django 4.1 on 2024-06-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harmoniconnect", "0003_serviceprovider_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceprovider",
            name="availability_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="offers",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="pricing",
            field=models.TextField(blank=True),
        ),
    ]
