# Generated by Django 4.1 on 2024-06-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harmoniconnect", "0004_serviceprovider_availability_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceprovider",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
