# Generated by Django 4.1 on 2024-06-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harmoniconnect", "0005_serviceprovider_is_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceprovider",
            name="name",
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="serviceprovider_name",
            field=models.CharField(default="Service provider name", max_length=255),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
