# Generated by Django 4.2.13 on 2024-06-23 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("harmoniconnect", "0009_alter_client_user_alter_serviceprovider_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="contact",
            field=models.CharField(default="000-000-0000", max_length=255),
        ),
        migrations.AddField(
            model_name="booking",
            name="email",
            field=models.EmailField(default="default@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="booking",
            name="location",
            field=models.CharField(default="Default Location", max_length=255),
        ),
        migrations.AddField(
            model_name="booking",
            name="name",
            field=models.CharField(default="Default Name", max_length=255),
        ),
        migrations.AlterField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service",
                to="harmoniconnect.service",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="harmoniconnect.serviceprovider",
            ),
        ),
    ]
