# Generated by Django 4.2.13 on 2024-06-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harmoniconnect", "0013_client_location_client_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
